//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Velib.VelibSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibSOAP.IVelibOperations")]
    public interface IVelibOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getCities", ReplyAction="http://tempuri.org/IVelibOperations/getCitiesResponse")]
        string[] getCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getCities", ReplyAction="http://tempuri.org/IVelibOperations/getCitiesResponse")]
        System.Threading.Tasks.Task<string[]> getCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getStations", ReplyAction="http://tempuri.org/IVelibOperations/getStationsResponse")]
        string[] getStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getStations", ReplyAction="http://tempuri.org/IVelibOperations/getStationsResponse")]
        System.Threading.Tasks.Task<string[]> getStationsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getAvailableBikes", ReplyAction="http://tempuri.org/IVelibOperations/getAvailableBikesResponse")]
        int getAvailableBikes(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperations/getAvailableBikes", ReplyAction="http://tempuri.org/IVelibOperations/getAvailableBikesResponse")]
        System.Threading.Tasks.Task<int> getAvailableBikesAsync(string city, string station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibOperationsChannel : Client_Velib.VelibSOAP.IVelibOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibOperationsClient : System.ServiceModel.ClientBase<Client_Velib.VelibSOAP.IVelibOperations>, Client_Velib.VelibSOAP.IVelibOperations {
        
        public VelibOperationsClient() {
        }
        
        public VelibOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCities() {
            return base.Channel.getCities();
        }
        
        public System.Threading.Tasks.Task<string[]> getCitiesAsync() {
            return base.Channel.getCitiesAsync();
        }
        
        public string[] getStations(string city) {
            return base.Channel.getStations(city);
        }
        
        public System.Threading.Tasks.Task<string[]> getStationsAsync(string city) {
            return base.Channel.getStationsAsync(city);
        }
        
        public int getAvailableBikes(string city, string station) {
            return base.Channel.getAvailableBikes(city, station);
        }
        
        public System.Threading.Tasks.Task<int> getAvailableBikesAsync(string city, string station) {
            return base.Channel.getAvailableBikesAsync(city, station);
        }
    }
}
